using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using server.Models.Surveys;

namespace server.Models{
    public class SurveyResponse
    {
        public int Id { get; set; }  // Changed from string to int, will be auto-generated by DB
        
        [ForeignKey("SurveyTemplate")]
        public int SurveyTemplateId { get; set; }  // Links to which survey
        public SurveyTemplate? SurveyTemplate { get; set; }  // Navigation property
        
        public int ContactId { get; set; }  // Who answered it
        public Contact Contact { get; set; } = new Contact(); // Navigation property
        public List<SurveyResponseAnswer> Answers { get; set; } = new List<SurveyResponseAnswer>();  // Their answers
        public DateTime CreatedDateTime { get; set; } = DateTime.UtcNow;
        public DateTime StartedAt { get; set; }
        public DateTime? CompletedAt { get; set; }

        [Required]
        public Guid ResponseGuid { get; set; } = Guid.NewGuid(); // Unique identifier for the response
    }
}